"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.15.
"""

from pathlib import Path
import os

# 🛠️ FIXED: Resolves paths correctly from the nested inner core folder
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-kk*(yim+x!)4$)%ntnw&nd&z9u69b11@=2^6!@j^fn&)b-70!a'

# 💻 FIXED: Changed to True so images and local styling render properly
DEBUG = False

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '49.13.162.124']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'booking',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Look for templates in the outer core folder
        'DIRS': [BASE_DIR / 'templates'], 
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'booking.context_processors.language_context',  
                'booking.context_processors.cart_counter_processor',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# 🛠️ Database Setup: Completely Server-Free local SQLite engine
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# 🖼️ Static & Media Files Handling (Fixed pathing links)
STATIC_URL = 'static/'

# 🛠️ THE FINAL FIX: Point this directly to BASE_DIR so it finds the folder inside 'core'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]



# Destination for collectstatic command
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
LOGIN_URL = 'login'


# # =====================================================================
# # MANDATORY EMAIL VALIDATION INFRASTRUCTURE (GMAIL SMTP SSL RELAY)
# # =====================================================================
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 465

# EMAIL_USE_TLS = False
# EMAIL_USE_SSL = True  

# EMAIL_HOST_USER = 'dhanushdsm6351364@gmail.com'
# EMAIL_HOST_PASSWORD = 'kdbj jhfn jggj imed'  
# DEFAULT_FROM_EMAIL = '"Ganesha Restaurant" <dhanushdsm6351364@gmail.com>'
# EMAIL_TIMEOUT = 10


# # =====================================================================
# # LIVE PHONE GATEWAY INFRASTRUCTURE (TWILIO SMS API)
# # =====================================================================
# TWILIO_ACCOUNT_SID = 'AC0a49258e955f071d1ae9c86c9c8144b1'
# TWILIO_AUTH_TOKEN = '4b4408ed21a5d2d18bf64a351ac6ef6b'
# TWILIO_PHONE_NUMBER = '+16516775864'