"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-kk*(yim+x!)4$)%ntnw&nd&z9u69b11@=2^6!@j^fn&)b-70!a'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'booking',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'], # Or whatever your custom DIRS list is set to
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'booking.context_processors.language_context',  # 🚀 Clean global language hook injection
            ],
        },
    },
]


WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

import os

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

LOGIN_URL = 'login'

# core/settings.py

# =====================================================================
# LIVE EMAIL NETWORK INFRASTRUCTURE (GMAIL SMTP RELAY)
# =====================================================================
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# CRITICAL: Replace with your actual Gmail address and Gmail App Password
EMAIL_HOST_USER = 'dhanushdsm6351364@gmail.com'
EMAIL_HOST_PASSWORD = 'xmzs chza wfhk jfpn' # 16-character Google App Password
DEFAULT_FROM_EMAIL = 'dhanushdsm6351364@gmail.com'

# =====================================================================
# LIVE PHONE GATEWAY INFRASTRUCTURE (TWILIO SMS API)
# =====================================================================
# Sign up at Twilio.com to get these testing API environment values
TWILIO_ACCOUNT_SID = 'AC0a49258e955f071d1ae9c86c9c8144b1'
TWILIO_AUTH_TOKEN = 'a203e0acd71d5e5ffcc8928095810462'
TWILIO_PHONE_NUMBER = '+16516775864' # Your virtual Twilio sender number

# C:/Users/mdhan/Desktop/skrt/core/core/settings.py

# Live SMTP Configuration Matrix
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'                      # Your mail server host domain
EMAIL_PORT = 587                                   # TLS Port mapping 
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'dhanushdsm6351364@gmail.com' # The restaurant's email address
EMAIL_HOST_PASSWORD = 'xmzs chza wfhk jfpn'        # Your secure Google App Password
DEFAULT_FROM_EMAIL = '"Ganesha Restaurant" <dhanushdsm6351364@gmail.com>'
