# Generated by Django 5.2.15 on 2026-06-09 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_foodcategory_remove_bookingorder_coupon_applied_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodcategory',
            name='icon',
            field=models.CharField(blank=True, help_text='Emoji for UI representation (e.g., 🍕)', max_length=10),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='diet_type',
            field=models.CharField(choices=[('VEG', 'Vegetarian 🟢'), ('NON-VEG', 'Non-Vegetarian 🔴'), ('VEGAN', 'Vegan 🌱')], default='VEG', max_length=10),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='is_chefs_special',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='foodorder',
            name='room_or_table_number',
            field=models.CharField(blank=True, help_text='Required for Room Service or Table Dining', max_length=20),
        ),
        migrations.AddField(
            model_name='foodorder',
            name='service_type',
            field=models.CharField(choices=[('ROOM_SERVICE', 'In-Room Dining 🛏️'), ('TABLE_DINING', 'Table Service 🍽️'), ('DELIVERY', 'Doorstep Delivery 🚗')], default='ROOM_SERVICE', max_length=20),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='description',
            field=models.TextField(blank=True, help_text='Ingredients or preparation summary'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='foodorder',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='foodorder',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='foodorder',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='foodorder',
            name='status',
            field=models.CharField(choices=[('PLACED', 'Order Received'), ('KITCHEN_ACCEPTED', 'Accepted by Chef'), ('PREPARING', 'In Preparation'), ('DISPATCHED', 'Out for Delivery / Serving'), ('DELIVERED', 'Served / Completed'), ('CANCELLED', 'Cancelled')], default='PLACED', max_length=20),
        ),
        migrations.AlterField(
            model_name='foodorder',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
