# Generated by Django 5.2.15 on 2026-06-11 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_foodcategory_icon_fooditem_diet_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='diet_type',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='is_chefs_special',
        ),
        migrations.AddField(
            model_name='fooditem',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload dish image from hotel page', null=True, upload_to='dishes/'),
        ),
        migrations.AlterField(
            model_name='foodcategory',
            name='icon',
            field=models.CharField(blank=True, help_text='e.g., 🍕', max_length=10),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.fooditem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_address', models.TextField()),
                ('phone_number', models.CharField(max_length=15)),
                ('payment_method', models.CharField(choices=[('PAYPAL', 'PayPal 💳'), ('CARD', 'Credit Card 🏦'), ('COD', 'Cash on Delivery 💵')], default='COD', max_length=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PLACED', 'Order Received'), ('PREPARING', 'In Kitchen'), ('DELIVERED', 'Served')], default='PLACED', max_length=20)),
                ('is_notified', models.BooleanField(default=False, help_text='Flags real-time audio pings')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coupon_applied', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderBreakdownItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_item_name', models.CharField(max_length=120)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='booking.ordersummary')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('address', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='FoodOrder',
        ),
    ]
