# Generated by Django 5.2.15 on 2026-06-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_remove_fooditem_diet_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fooditem',
            old_name='description',
            new_name='description_de',
        ),
        migrations.RenameField(
            model_name='fooditem',
            old_name='name',
            new_name='name_de',
        ),
        migrations.RemoveField(
            model_name='foodcategory',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='foodcategory',
            name='name',
        ),
        migrations.AddField(
            model_name='foodcategory',
            name='name_de',
            field=models.CharField(default='Temporary', help_text='e.g., Vorspeisen', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foodcategory',
            name='name_en',
            field=models.CharField(default='Temporary', help_text='e.g., Starters', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fooditem',
            name='description_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='diet_type',
            field=models.CharField(choices=[('VEG', 'Veg 🟢'), ('NON_VEG', 'Non-Veg 🔴')], default='VEG', max_length=10),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='item_type',
            field=models.CharField(choices=[('FOOD', 'Food / Speise (7% VAT)'), ('BEVERAGE', 'Beverage / Getränk (19% VAT)')], default='FOOD', max_length=15),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='name_en',
            field=models.CharField(default='Temporary', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordersummary',
            name='estimated_time',
            field=models.CharField(default='Pending Manager Allocation', max_length=50),
        ),
        migrations.AddField(
            model_name='ordersummary',
            name='gst_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ordersummary',
            name='order_type',
            field=models.CharField(choices=[('DELIVERY', 'Delivery / Lieferung'), ('PICKUP', 'Pickup / Abholung'), ('DINE_IN', 'Dine-In / Vor Ort')], default='DELIVERY', max_length=15),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dishes/'),
        ),
        migrations.AlterField(
            model_name='ordersummary',
            name='delivery_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordersummary',
            name='is_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ordersummary',
            name='payment_method',
            field=models.CharField(choices=[('PAYPAL', 'PayPal'), ('CARD', 'Card'), ('COD', 'COD')], default='COD', max_length=10),
        ),
        migrations.AlterField(
            model_name='ordersummary',
            name='status',
            field=models.CharField(choices=[('PLACED', 'Received / Erhalten'), ('PREPARING', 'Kitchen / In der Küche'), ('OUT_FOR_DELIVERY', 'Out for Delivery / Unterwegs'), ('DELIVERED', 'Completed / Abgeschlossen')], default='PLACED', max_length=25),
        ),
    ]
