# Generated by Django 5.2.15 on 2026-06-12 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_userprofile_email_verified_userprofile_otp_expiry_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='min_order_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='coupon',
            name='specific_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exclusive_coupons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ordersummary',
            name='status',
            field=models.CharField(choices=[('PLACED', 'Received / Erhalten'), ('PREPARING', 'Kitchen / In der Küche'), ('OUT_FOR_DELIVERY', 'Out for Delivery / Unterwegs'), ('DELIVERED', 'Completed / Abgeschlossen'), ('CANCELLED', 'Cancelled / Storniert')], default='PLACED', max_length=25),
        ),
    ]
