# Generated by Django 5.2.15 on 2026-06-12 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_coupon_used_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersummary',
            name='canceled_by',
            field=models.CharField(blank=True, choices=[('CUSTOMER', 'Customer'), ('OWNER', 'Owner / Staff')], max_length=20, null=True),
        ),
    ]
