# Generated by Django 5.2.15 on 2026-06-12 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_ordersummary_canceled_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersummary',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
