"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.15.
"""

from pathlib import Path
import os

# 🛠️ FIXED: Resolves paths correctly from the nested inner core folder
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-kk*(yim+x!)4$)%ntnw&nd&z9u69b11@=2^6!@j^fn&)b-70!a'

# 💻 PRODUCTION WARNING: Keep False on cPanel so errors don't leak raw credentials
DEBUG = True

# 🔒 SECURITY PACKET: ALLOWED DOMAINS ROUTING MATRIX
ALLOWED_HOSTS = [
    'ganeshamuehlacker.com',       # 🎯 Main live domain name
    'www.ganeshamuehlacker.com',   # 🎯 www prefix alternative version
    '127.0.0.1',                    # Local development safety fallback
    'localhost',
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'booking.apps.BookingConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    
    # 🎯 INJECTED WHITENOISE MIDDLEWARE: Must sit exactly below SecurityMiddleware
    # Allows Django to cleanly serve the hero images and layouts when DEBUG is False
    'whitenoise.middleware.WhiteNoiseMiddleware',
    
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'], 
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'booking.context_processors.language_context',  
                'booking.context_processors.cart_counter_processor',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

# =====================================================================
# 🗄️ PRODUCTION DATABASE SETUP: Native cPanel Engine (MySQL/MariaDB)
# =====================================================================
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'ganesham_food_new',             # 🎯 Your actual cPanel Database Name
        'USER': 'ganesham_food_new',            # 🎯 Your cPanel Database Username 
        'PASSWORD': 'Sky#Blue99',   # 🎯 Place your DB User password here
        'HOST': 'localhost',                    # Kept local for cPanel network routing
        'PORT': '3306',                         # Standard MySQL port
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        }
    }
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# 🖼️ Static & Media Files Handling (Fixed pathing links)
STATIC_URL = '/static/'

# 🛠️ THE FINAL FIX: Point this directly to BASE_DIR so it finds the folder inside 'core'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Destination for collectstatic command
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# 🎯 INJECTED WHITENOISE STORAGE: Optimizes and gzips assets automatically for web requests
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
LOGIN_URL = 'login'


# =====================================================================
# 💳 MOLLIE PAYMENT GATEWAY INTEGRATION CHANNELS (LIVE PRODUCTION CONFIGS)
# =====================================================================


# =====================================================================
# 📬 PRIVATE NATIVE CPANEL SMTP BACKEND ENGINE (UNCOMMENTED & OPERATIONAL)
# =====================================================================
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'localhost'                       # 🎯 Routes internally on this machine to bypass firewall
# EMAIL_PORT = 25                                # 🎯 Standard internal cPanel mail handler port
# EMAIL_USE_TLS = False                          # Clear-text internal routing; TLS not needed
# EMAIL_USE_SSL = False                          # Clear-text internal routing; SSL not needed
# EMAIL_HOST_USER = ''
# EMAIL_HOST_PASSWORD = 'Your password'             # Your private mailbox password
# DEFAULT_FROM_EMAIL = ''
# EMAIL_TIMEOUT = 10
