# Generated by Django 5.2.15 on 2026-06-18 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_coupon_applicable_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordersummary',
            name='order_type',
        ),
        migrations.AddField(
            model_name='ordersummary',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending / Ausstehend'), ('Paid', 'Paid / Erfolgreich gezahlt'), ('Cancelled', 'Cancelled / Storniert'), ('Failed', 'Failed / Fehlgeschlagen')], default='Pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='ordersummary',
            name='payment_method',
            field=models.CharField(choices=[('PAYPAL', 'PayPal'), ('CARD', 'Card'), ('COD', 'COD'), ('MOLLIE', 'Mollie Gateway')], default='COD', max_length=10),
        ),
    ]
