# Generated by Django 5.2.15 on 2026-06-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_ordersummary_order_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersummary',
            name='order_type',
            field=models.CharField(choices=[('DELIVERY', 'Delivery / Lieferung'), ('PICKUP', 'Pickup / Abholung'), ('DINE_IN', 'Dine-In / Vor Ort')], default='DELIVERY', max_length=15),
        ),
    ]
