# Generated by Django 5.2.15 on 2026-06-19 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_ordersummary_order_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersummary',
            name='status',
            field=models.CharField(choices=[('verifying', 'Verifying / System-Validierung'), ('processing', 'Processing / In Bearbeitung'), ('failed', 'Payment Failed / Fehlgeschlagen'), ('success', 'Payment Success / Erfolgreich'), ('ordered', 'Ordered / Received / Erhalten'), ('preparing', 'Kitchen / Preparing / In der Küche'), ('delivered', 'Out for Delivery / Unterwegs'), ('completed', 'Completed / Abgeschlossen'), ('cancelled', 'Cancelled / Storniert')], default='verifying', max_length=25),
        ),
    ]
