# Generated by Django 5.2.15 on 2026-06-20 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_ordersummary_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='promos/')),
                ('video', models.FileField(blank=True, null=True, upload_to='promos/')),
                ('notes_en', models.TextField(blank=True, help_text='Announcement description notes in English', null=True)),
                ('notes_de', models.TextField(blank=True, help_text='Ankündigungstext auf Deutsch', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
